/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/logSignIn`; params?: Router.UnknownInputParams; } | { pathname: `/utils`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/pages/home`; params?: Router.UnknownInputParams; } | { pathname: `/pages/host/court`; params?: Router.UnknownInputParams; } | { pathname: `/pages/host`; params?: Router.UnknownInputParams; } | { pathname: `/pages/host/queue`; params?: Router.UnknownInputParams; } | { pathname: `/pages/player/games`; params?: Router.UnknownInputParams; } | { pathname: `/pages/player`; params?: Router.UnknownInputParams; } | { pathname: `/pages/player/stats`; params?: Router.UnknownInputParams; } | { pathname: `/pages/user`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/logSignIn`; params?: Router.UnknownOutputParams; } | { pathname: `/utils`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/home`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/host/court`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/host`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/host/queue`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/player/games`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/player`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/player/stats`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/user`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/logSignIn${`?${string}` | `#${string}` | ''}` | `/utils${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/pages/home${`?${string}` | `#${string}` | ''}` | `/pages/host/court${`?${string}` | `#${string}` | ''}` | `/pages/host${`?${string}` | `#${string}` | ''}` | `/pages/host/queue${`?${string}` | `#${string}` | ''}` | `/pages/player/games${`?${string}` | `#${string}` | ''}` | `/pages/player${`?${string}` | `#${string}` | ''}` | `/pages/player/stats${`?${string}` | `#${string}` | ''}` | `/pages/user${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/logSignIn`; params?: Router.UnknownInputParams; } | { pathname: `/utils`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/pages/home`; params?: Router.UnknownInputParams; } | { pathname: `/pages/host/court`; params?: Router.UnknownInputParams; } | { pathname: `/pages/host`; params?: Router.UnknownInputParams; } | { pathname: `/pages/host/queue`; params?: Router.UnknownInputParams; } | { pathname: `/pages/player/games`; params?: Router.UnknownInputParams; } | { pathname: `/pages/player`; params?: Router.UnknownInputParams; } | { pathname: `/pages/player/stats`; params?: Router.UnknownInputParams; } | { pathname: `/pages/user`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
